### PR TITLE
issue-125_neo4j-fix-constraint-creation

### LINKED ISSUE #125: [BUG] Neo4j EmbeddingStore fails to build if NODE_KEY constraint exist
**Describe the bug**

When an existing constraint of type `NODE_KEY` exist for the given `label` and `idProperty`, the `neo4jEmbeddingStore` fails to be created due to its `createUniqueConstraint` method not checking properly if an existing constraint exist.

**Log and Stack trace**
```
org.neo4j.driver.exceptions.ClientException: Constraint already exists: Constraint( id=4, name='constraint_2ddb6c03', type='NODE KEY', schema=(:Section {id}), ownedIndex=3 )

	at org.neo4j.driver.internal.util.Futures.blockingGet(Futures.java:64)
	at org.neo4j.driver.internal.InternalSession.run(InternalSession.java:63)
	at org.neo4j.driver.internal.InternalSession.run(InternalSession.java:48)
	at org.neo4j.driver.internal.AbstractQueryRunner.run(AbstractQueryRunner.java:32)
	at org.neo4j.driver.internal.AbstractQueryRunner.run(AbstractQueryRunner.java:47)
	at dev.langchain4j.store.embedding.neo4j.Neo4jEmbeddingStore.createUniqueConstraint(Neo4jEmbeddingStore.java:256)
	at dev.langchain4j.store.embedding.neo4j.Neo4jEmbeddingStore.createSchema(Neo4jEmbeddingStore.java:246)
	at dev.langchain4j.store.embedding.neo4j.Neo4jEmbeddingStore.<init>(Neo4jEmbeddingStore.java:140)
	at dev.langchain4j.store.embedding.neo4j.Neo4jEmbeddingStore$Neo4jEmbeddingStoreBuilder.build(Neo4jEmbeddingStore.java:88)
	at dev.ikwattro.ai.ProcessAdocTest.docs_naive_rag(ProcessAdocTest.java:120)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
```

**To Reproduce**

Create a unique constraint for the `Section` label and `id` property

```
CREATE CONSTRAINT section_id_nk 
FOR (n:Section)
REQUIRE n.id IS NODE KEY
```

Build a Neo4jEmbeddingStore

```
var neo4jEmbeddingStore = Neo4jEmbeddingStore.builder()
                .withBasicAuth("bolt://localhost:7687", "neo4j", "password")
                .databaseName("test")
                .label("Section")
                .embeddingProperty("embedding")
                .dimension(384)
                .textProperty("text")
                .indexName("sectionEmbeddings")
                .build();
```

**Expected behavior**

The embedding store can be instantiated.

**Please complete the following information:**
- LangChain4j version: 1.0.0-beta2
- LLM(s) used:  openai
- Java version: 21

**Additional context**

Suggestion to use this query for existing constraint check

```
SHOW CONSTRAINTS 
WHERE $label IN labelsOrTypes 
AND $property IN properties 
AND type IN ['NODE_KEY', 'UNIQUENESS']
```
And check if result is empty

/cc @vga91 @jexp

### PR DESCRIPTION
**Pull request by ikwattro**
## Issue

Closes #125  - Embedding store cannot be instantiated if node key constraint exist

## Change

- Added existing constraint check before constraint creation
- Upgrade to Neo4j Enterprise container for tests, `NODE KEY` constraint not available in Neo4j community

## General checklist

- [X] There are no breaking changes
- [X] I have added unit and integration tests for my change
- [X] I have manually run all the unit tests in _all_ modules, and they are all green
- [X] I have manually run all integration tests in the module I have added/changed, and they are all green

- [ ] I have added/updated the [documentation](https://github.com/langchain4j/langchain4j/tree/main/docs/docs)
- [ ] I have added an example in the [examples repo](https://github.com/langchain4j/langchain4j-examples) (only for "big" features)
- [ ] I have added/updated [Spring Boot starter(s)](https://github.com/langchain4j/langchain4j-spring) (if applicable)

## Checklist for adding new maven module

- [ ] I have added my new module in the root `pom.xml` and `langchain4j-community-bom/pom.xml`

## Checklist for adding new embedding store integration

- [ ] I have added a `{NameOfIntegration}EmbeddingStoreIT` that extends from either `EmbeddingStoreIT` or `EmbeddingStoreWithFilteringIT`
- [ ] I have added a `{NameOfIntegration}EmbeddingStoreRemovalIT` that extends from `EmbeddingStoreWithRemovalIT`

## Checklist for changing existing embedding store integration

- [ ] I have manually verified that the `{NameOfIntegration}EmbeddingStore` works correctly with the data persisted using the latest released version of LangChain4j

### CODE REVIEW

**Comment by ikwattro** [comment]
@vga91 @jexp ^^

**Review by jexp — APPROVED** [review]
LGTM thanks @ikwattro

File: embedding-stores/langchain4j-community-neo4j/src/test/java/dev/langchain4j/community/store/embedding/neo4j/Neo4jEmbeddingStoreBaseTest.java [hunk 1]
```diff
@@ -24,11 +24,13 @@ public abstract class Neo4jEmbeddingStoreBaseTest extends EmbeddingStoreIT {
     protected static final String USERNAME = "neo4j";
     protected static final String ADMIN_PASSWORD = "adminPass";
     protected static final String LABEL_TO_SANITIZE = "Label ` to \\ sanitize";
-    protected static final String NEO4J_VERSION = System.getProperty("neo4jVersion", "5.26");
+    protected static final String NEO4J_VERSION = System.getProperty("neo4jVersion", "5.26-enterprise");
```
Comment (Martin7-1) [inline embedding-stores/langchain4j-community-neo4j/src/test/java/dev/langchain4j/community/store/embedding/neo4j/Neo4jEmbeddingStoreBaseTest.java:27]: I'm wondering what is the difference between enterprise version and normal version.

Should we test on both version of them?

**Review by Martin7-1 — APPROVED** [review]
@ikwattro Thank you!
